services:
  odoo:
    image: odoo:19.0
    container_name: odoo_machado
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./controle_combustivel:/mnt/extra-addons/controle_combustivel
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: -- --database odoo_machado --init controle_combustivel --without-demo all

  db:
    image: postgres:16
    container_name: odoo_machado_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_db_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U odoo -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  odoo_db_data:
