services:
  odoo:
    image: odoo:19.0
    container_name: odoo_machado
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./controle_combustivel:/mnt/extra-addons/controle_combustivel
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: odoo_machado_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  odoo_db_data:
